### ISSUE TITLE
报错信息排版与定位

### ISSUE THREAD

**Issue by nobodxbodon** [FIRESIDE-STORY/yyc#1]
刚试了 node test.js，引入一个错误后，报错如下：
![Screen Shot 2021-02-25 at 8 55 33 AM](https://user-images.githubusercontent.com/392497/109188086-640eb180-7747-11eb-9bdb-9aca5461d9bc.png)
除了代码未分行外，似乎 ^ 由于中英文字符不等宽因而定位有偏差。
早先在 [木兰重现项目](https://gitee.com/MulanRevive/mulan-rework/issues/I1U2H5?from=project-issue) 也碰到类似定位问题。

**Comment by TIME-GATE** [comment]
打印1这个不是系统内置函数. 代码是否分行都不影响, 只要用空格分开就行

**Comment by nobodxbodon** [comment]
嗯我是特地引入了这个错误，想看看报错信息的内容和格式。
最近比较在意语言工具的报错信息（刚小结了木兰的 [在此](https://zhuanlan.zhihu.com/p/351483957)，它是词法语法分析后生成Python 语法树，机制差不多吧）

**Comment by TIME-GATE** [comment]
报错信息可以用内置的Error handle, 分别对应中文或英文, 考虑到使用的是V8引擎且支持调用原生的Node库, 直接打印错误栈更合适, 使用js作为中间代码的优点是可以无缝衔接NPM上的库.

**Comment by nobodxbodon** [comment]
期待继续雕琢。
